name: Python CI

on:
  push:
    branches: [ main, master ]  # This will run the workflow on push events to main or master branches.
  #pull_request:
    #branches: [ main, master ]  # This will also run the workflow on pull requests targeting main or master.

jobs:
  build:

    runs-on: ubuntu-latest  # Use the latest Ubuntu environment.

    strategy:
      matrix:
        python-version: [3.11]  # This will run the tests on three versions of Python.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check for requirements.txt
      run: test -f requirements.txt && echo "requirements.txt exists" || echo "requirements.txt does not exist"
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: Run Tests
      run: |
        pytest tests/ # Assuming your tests are in a directory called 'tests'.
